# Compose file의 버전
# docker-compose의 버전에 따라 사용할 수 있는 compose file 버전이 다르다. 도커-컴포즈 1.27.0 버전 이후 부터는 2.x와 3.x가 사용가능.
version: '3.0'

services:
  nginx:
    image: debian:buster
    # 조건에 관계없이 서비스를 활성 상태로 유지하기 위한 재시작 정책
    restart: always
    #ports:
    #  - "443:443"
  mariadb:
    image: debian:buster
    restart: always
    #expose:
    #  - "3306"
  wordpress:
    image: debian:buster
    restart: always
    #expose:
    #  - "9000"

networks:
  inception_net:


