# Compose file의 버전
# docker-compose의 버전에 따라 사용할 수 있는 compose file 버전이 다르다. 도커-컴포즈 1.27.0 버전 이후 부터는 2.x와 3.x가 사용가능.
version: '3.0'

services:
  nginx:
    #빌드할 Dockerfile 위치
    build: ./requirements/nginx/
    image: nginx
    # 조건에 관계없이 서비스를 활성 상태로 유지하기 위한 재시작 정책 -> https://serverfault.com/questions/884759/how-does-restart-always-policy-work-in-docker-compose
    restart: always
    ports:
      - "443:443"
    #environment:
  #mariadb:
  #  build: ./requirements/mariadb/
  #  image: mariadb
  #  restart: always
  #  expose:
  #    - "3306"
  #  environment:
  #wordpress:
  #  build: ./requirements/wordpress/
  #  image: wordpress
  #  restart: always
  #  expose:
  #    - "9000"
  #  environment:

networks:
  inception_net:


